### ISSUE TITLE
Add support for specifying string import paths

### ISSUE THREAD

**Issue by linkrope** [jacob-carlborg/dlp#2]
First, I tried

> $ dlp leaf-functions -Isource source/dlp/driver/main.d
> source/dlp/driver/application.d(24): Error: need `-J` switch to import text file `version`

While `dlp` supports option `-I`, there is currently no support for option `-J`.

**Comment by jacob-carlborg** [comment]
I took the liberty to split this into two separate issues. The other one being: https://github.com/jacob-carlborg/dlp/issues/3.
