### ISSUE TITLE
Build broken against dmd-master

### ISSUE THREAD

**Issue by MartinNowak** [jacob-carlborg/dlp#6]
Just FYI
https://buildkite.com/dlang/phobos/builds/4232#10246b2a-f73e-4bf0-a7c1-5ca3cc773d1f

```
../.dub/packages/ddc-0.0.4_2.094.1/ddc/src/dmd/dversion.d(57,27): Error: function `dmd.dversion.DebugSymbol.toChars` does not override any function
../.dub/packages/ddc-0.0.4_2.094.1/ddc/src/dmd/aggregate.d(23,8): Error: module `dmd.gluelayer` import `Symbol` not found, did you mean class `dmd.dsymbol.Dsymbol`?
...
```

**Comment by jacob-carlborg** [comment]
I don't know what BuildKite is doing, but it works perfectly fine locally and in GitHub Actions: https://github.com/jacob-carlborg/dlp/actions/runs/431205082.

**Comment by jacob-carlborg** [comment]
Dub doesn't pass these versions identifiers [1] to the compiler for some reason: [2].

[1] https://github.com/jacob-carlborg/ddc/blob/c64faa4d97f9727a0461358be402ec9a356e46c1/dub.sdl#L78-L83
[2] https://buildkite.com/dlang/ci/builds/797#59cd2942-6e58-4296-906d-4a9414bf670c

**Comment by jacob-carlborg** [comment]
@MartinNowak fixed: https://github.com/dlang/ci/pull/439.

**Comment by MartinNowak** [comment]
thx

**Comment by MartinNowak** [comment]
It's testing dmd master, so I guess you could expect some upcoming breakage for 2.095.x.

**Comment by jacob-carlborg** [comment]
I did test using DMD mater and it works for me. GitHub Action is testing using DMD master as well. It looks like Dub is broken.
